services:
  postgres:
    container_name: partnerhub-db-dev
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: partnerhub_dev
    ports:
      - "5432:5432"

  app:
    container_name: partnerhub-app-dev
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/partnerhub_dev
      SPRING_DATASOURCE_USERNAME: dev_user
      SPRING_DATASOURCE_PASSWORD: dev_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: dev

  prometheus:
    container_name: prometheus-dev

  grafana:
    container_name: grafana-dev

  swagger-ui:
    container_name: swagger-ui-dev