@startuml

left to right direction

entity "tb_user" as user {
*id : BIGINT <<PK>>
--
name : VARCHAR(120)
email : VARCHAR(200) <<UQ>>
password : VARCHAR(129)
enabled : BOOLEAN
created_at : TIMESTAMP
updated_at : TIMESTAMP
}

entity "tb_user_external_project" as project {
*id : VARCHAR(200) <<PK>>
*user_id : BIGINT <<PK, FK>>
--
name : VARCHAR(120)
description : TEXT
url : VARCHAR(255)
created_at : TIMESTAMP
updated_at : TIMESTAMP
}

user ||--o{ project : has

@enduml
